import type { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { data: session } = useSession()
  let canvas
  let image: HTMLImageElement
  let ctx: CanvasRenderingContext2D
  const [face, setFace] = useState<number>(0)

  const changeFace = (isReverse = false) => {
    canvas = document.getElementById('monster') as HTMLCanvasElement
    ctx = canvas.getContext('2d') as CanvasRenderingContext2D
    image = new window.Image(30, 30)
    let faceIdx

    ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height)
    faceIdx = isReverse ? Math.abs((face + 3) % 4) : (face + 1) % 4

    image.src = `/face${faceIdx}.png`
    image.onload = function () {
      ctx.drawImage(image, 0, 0)
    }
    setFace(faceIdx)
  }

  useEffect(() => {
    changeFace()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline"> 포동 포동</h1>
        {session ? (
          <>
            안녕! {session.user?.name} <br />
            <button onClick={() => signOut()}>로그아웃</button>
          </>
        ) : (
          <>
            Not signed in <br />
            <button onClick={() => signIn('kakao')}>카카오 로그인</button>
            <button onClick={() => signIn('google')}>구글 로그인</button>
            <button onClick={() => signIn('twitter')}>트위터 로그인</button>
          </>
        )}

        <p className={styles.description}>
          Get started by editing
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Image
            src="/arrow-left.png"
            alt="왼쪽 버튼"
            width={50}
            height={50}
            onClick={() => changeFace(true)}
            className={styles.arrowBtn}
          />
          <div className={styles.character}>
            <canvas id="monster" width="150" height="300"></canvas>
          </div>
          <Image
            src="/arrow-right.png"
            alt="오른쪽 버튼"
            width={50}
            height={50}
            onClick={() => changeFace()}
            className={styles.arrowBtn}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>

  )
}

export default Home
