import type { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Character from './components/Character'

const Home: NextPage = () => {
  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">HexHead!</a>
        </h1>
        {session ? (
          <>
            안녕! {session.user?.name} <br />
            <button onClick={() => signOut()}>로그아웃</button>
          </>
        ) : (
          <>
            Not signed in <br />
            <button onClick={() => signIn('kakao')}>카카오 로그인</button>
            <button onClick={() => signIn('google')}>구글 로그인</button>
            <button onClick={() => signIn('twitter')}>트위터 로그인</button>
          </>
        )}

        <p className={styles.description}>
          Get started by editing
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <Character />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
